// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Jamnagar, Gujarat",
  category: "",
  address: "",
  phone: "",
  email: "",
  website: "",
  mapUrl: "https://www.google.com/maps/@22.4135728,70.0564298,3a,75y,159.53h,90t/data=!3m7!1e1!3m5!1sJ0Rlm68EpTEketLhtU4CVg!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D0%26panoid%3DJ0Rlm68EpTEketLhtU4CVg%26yaw%3D159.53156!7i16384!8i8192?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D",
  latitude: "22.4135728",
  longitude: "70.0564298",
  rating: "",
  reviewsCount: "",
  openingHours: "",
  logo: null,
  images: [],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "jamnagar's local gem",
  heroDescription: "located in the heart of gujarat, jamnagar is a local business that thrives on community spirit. with a strong focus on local culture, we strive to deliver unique experiences. from traditional gujarati cuisine to vibrant local events, we have something for everyone.",
  aboutTitle: "our jamnagar story",
  aboutText: "our business is nestled in the null area, where the sound of the sea and the smell of traditional gujarati food fill the air. we're proud to be a part of this vibrant community, and we're committed to delivering exceptional services that reflect the warmth and hospitality of jamnagar. our team is dedicated to providing personalized experiences that make you feel at home.",
  services: [
    { icon: "🏙️", title: "Gujarat Tour Packages", description: "explore the rich history and culture of gujarat with our curated tour packages, starting from ₹1199" },
    { icon: "🍴", title: "Local Cuisine Workshops", description: "learn the art of traditional gujarati cooking with our expert chefs, priced at ₹899 per session" },
    { icon: "🎨", title: "Jamnagar Art Walks", description: "discover the vibrant street art scene of jamnagar with our guided walks, available for ₹699" },
    { icon: "📚", title: "Gujarati Language Classes", description: "learn the basics of gujarati language and culture with our interactive classes, starting from ₹1499" },
    { icon: "📸", title: "Jamnagar Photography Tours", description: "capture the beauty of jamnagar with our expert photography guides, priced at ₹1999" },
    { icon: "🏞️", title: "Gujarat Nature Escapes", description: "escape to the pristine natural landscapes of gujarat with our curated nature tours, starting from ₹2399" }
  ],
  whyChooseUs: [
    { icon: "💯", title: "Local Expertise", description: "our team has in-depth knowledge of jamnagar and gujarat, ensuring that you get the most authentic experiences" },
    { icon: "👥", title: "Community Focus", description: "we're committed to supporting local businesses and promoting community development" },
    { icon: "📈", title: "Personalized Services", description: "we offer tailored services that cater to your unique needs and preferences" }
  ],
  testimonials: [
    { name: "Pallavi Mehta", role: "Local Resident", text: "i've been using jamnagar's local business services for years, and i must say that their gujarat tour packages are unbeatable. the team is knowledgeable and friendly, and they make sure that you have a memorable experience.", rating: 5 },
    { name: "Pankaj Patel", role: "Tourist", text: "i recently took a jamnagar art walk with this business, and it was an eye-opener. the guide was informative and passionate, and i loved the street art scene of jamnagar. i highly recommend their services to anyone visiting the city.", rating: 5 },
    { name: "Preeti Shah", role: "Foodie", text: "i'm a big fan of gujarati cuisine, and jamnagar's local business has the best local cuisine workshops in town. the chefs are skilled and patient, and the food is delicious. i've learned so much from their classes, and i highly recommend them to anyone who loves cooking.", rating: 5 }
  ],
  faq: { items: [{ question: "what is the best time to visit jamnagar?", answer: "the best time to visit jamnagar is during the winter months, from october to february, when the weather is pleasant and cool." },
    { question: "how do i get to jamnagar?", answer: "jamnagar is well-connected by road, rail, and air. you can take a flight to jamnagar airport or a train to jamnagar railway station, or drive down from nearby cities like ahmedabad or rajkot." },
    { question: "what are the must-try dishes in jamnagar?", answer: "jamnagar is famous for its traditional gujarati cuisine, which includes dishes like khakhra, thepla, and undhiyu. you should also try the local street food, like fafda and jalebi." },
    { question: "can i customize my tour package?", answer: "yes, we offer customized tour packages to suit your needs and preferences. please contact us to discuss your requirements and we'll create a tailored package for you." },
    { question: "what is the cancellation policy?", answer: "our cancellation policy varies depending on the service. please check our website or contact us for more information." },
    { question: "how do i book a service with jamnagar's local business?", answer: "you can book a service with us by visiting our website, sending us an email, or giving us a call. we'll be happy to assist you and answer any questions you may have." }] },
  ctaTitle: "explore jamnagar with us",
  ctaDescription: "discover the beauty and charm of jamnagar with our expert guides and tailored services. get in touch with us to plan your next adventure.",
  ctaButtonText: "book now",
  metaDescription: "jamnagar's local business offers unique experiences and services in gujarat",
};

export const siteConfig = {
  layout: "brutalist",
  theme: "elegant",
  sections: ["gallery", "about", "services", "gallery", "testimonials", "faq", "contact"],
  heroVariant: "masonry-layout",
  navStyle: "transparent-navbar",
  animationStyle: "minimal-no-animation",
  cardStyle: "rounded-xl bg-gradient-to-br from-card to-transparent",
  darkMode: false,
};
