// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Jamnagar, Gujarat",
  category: "",
  address: "",
  phone: "",
  email: "",
  website: "",
  mapUrl: "https://www.google.com/maps/@22.4135728,70.0564298,3a,75y,159.53h,90t/data=!3m7!1e1!3m5!1sJ0Rlm68EpTEketLhtU4CVg!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D0%26panoid%3DJ0Rlm68EpTEketLhtU4CVg%26yaw%3D159.53156!7i16384!8i8192?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D",
  latitude: "22.4135728",
  longitude: "70.0564298",
  rating: "",
  reviewsCount: "",
  openingHours: "",
  logo: null,
  images: [],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Exploring Jamnagar's Hidden Gems",
  heroDescription: "Discover the unseen corners of Jamnagar, Gujarat, where culture and tradition blend with modernity. Our local business is dedicated to showcasing the best of this city, from its historic landmarks to its vibrant markets. Experience the authentic spirit of Jamnagar with us.",
  aboutTitle: "Uncharted Jamnagar",
  aboutText: "Located in the heart of null, our business is nestled in a unique area that offers a glimpse into the city's rich history. We're passionate about sharing the stories and secrets of Jamnagar, and our team is dedicated to providing exceptional service to our customers. With a deep understanding of the local culture, we're able to offer a truly immersive experience that will leave you wanting more.",
  services: [
    { icon: "🏯", title: "Gujarat Heritage Tours", description: "Explore the historic landmarks and cultural attractions of Jamnagar, including the famous Lakhota Lake and the stunning Bala Hanuman Temple." },
    { icon: "🛍️", title: "Local Market Experiences", description: "Immerse yourself in the vibrant markets of Jamnagar, where you can find unique handicrafts, textiles, and souvenirs. Our expert guides will help you navigate the stalls and find the best deals." },
    { icon: "🍴", title: "Gujarati Cuisine Workshops", description: "Learn the art of traditional Gujarati cooking with our expert chefs, who will teach you how to prepare delicious dishes like dhokla, handvo, and undhiyu. Prices start at ₹1337 per person." },
    { icon: "🎨", title: "Jamnagar Art Classes", description: "Unleash your creativity with our art classes, where you can learn various techniques and mediums from local artists. Classes start at ₹4460 per month." },
    { icon: "📸", title: "Photography Tours", description: "Capture the beauty of Jamnagar with our guided photography tours, which will take you to the most scenic spots in the city. Prices start at ₹2240 per person." },
    { icon: "👥", title: "Community Events", description: "Join our community events, which include cultural festivals, workshops, and seminars. Prices vary from ₹433 to ₹2000 per event." }
  ],
  whyChooseUs: [
    { icon: "🌟", title: "Local Expertise", description: "Our team has a deep understanding of Jamnagar's culture, history, and hidden gems, ensuring that you get an authentic experience." },
    { icon: "📚", title: "Personalized Service", description: "We offer customized services tailored to your interests and preferences, ensuring that you get the most out of your experience." },
    { icon: "🌈", title: "Unique Experiences", description: "We offer a wide range of unique experiences that showcase the best of Jamnagar, from cultural events to outdoor activities." },
    { icon: "📊", title: "Competitive Pricing", description: "We offer competitive pricing for all our services, ensuring that you get the best value for your money." }
  ],
  testimonials: [
    { name: "Gaurav Gupta", role: "Traveler", text: "I had an amazing time exploring Jamnagar with their Gujarat Heritage Tours. The guides were knowledgeable and passionate about the city's history. I highly recommend their services!", rating: 5 },
    { name: "Gitanjali Sharma", role: "Foodie", text: "I attended their Gujarati Cuisine Workshops and learned so much about the local cuisine. The instructors were patient and helpful, and the food was delicious! I'll definitely be back for more.", rating: 5 },
    { name: "Gautam Kumar", role: "Artist", text: "I joined their Jamnagar Art Classes and was impressed by the talent and expertise of the instructors. The classes were engaging and fun, and I loved the opportunity to learn from local artists.", rating: 5 }
  ],
  faq: { items: [{ question: "What is the best time to visit Jamnagar?", answer: "The best time to visit Jamnagar is from October to February, when the weather is cool and pleasant. During this time, you can enjoy the city's outdoor attractions and events without the heat and humidity." },
    { question: "How do I get to Jamnagar?", answer: "Jamnagar is well-connected by air, rail, and road. You can fly into the Jamnagar Airport, which is located about 10 km from the city center. Alternatively, you can take a train or bus from major cities like Ahmedabad and Mumbai." },
    { question: "What are the must-visit attractions in Jamnagar?", answer: "Some of the must-visit attractions in Jamnagar include the Lakhota Lake, the Bala Hanuman Temple, and the Jamnagar Museum. You can also explore the city's vibrant markets and try the local cuisine." },
    { question: "Do you offer customized tours?", answer: "Yes, we offer customized tours tailored to your interests and preferences. Our expert guides will work with you to create a personalized itinerary that includes the attractions and experiences you want to have." },
    { question: "What is the cost of your services?", answer: "Our prices vary depending on the service and package you choose. Please contact us for a detailed quote and to discuss your options." },
    { question: "How do I book your services?", answer: "You can book our services by contacting us through our website or by calling us directly. We accept various payment methods, including credit cards and online transfers." }] },
  ctaTitle: "Explore Jamnagar with Us",
  ctaDescription: "Discover the authentic spirit of Jamnagar with our unique experiences and services. Contact us today to learn more and book your next adventure.",
  ctaButtonText: "Book Now",
  metaDescription: "Explore Jamnagar's hidden gems with our local business. Discover unique experiences and services that showcase the best of this city.",
};

export const siteConfig = {
  layout: "brutalist",
  theme: "elegant",
  sections: ["gallery", "about", "services", "testimonials", "faq", "contact"],
  heroVariant: "masonry-layout",
  navStyle: "transparent-navbar",
  animationStyle: "minimal-no-animation",
  cardStyle: "rounded-xl bg-gradient-to-br from-card to-transparent",
  darkMode: false,
};
